### ISSUE TITLE
IC http proxy icon is not visible enough

### ISSUE THREAD

**Issue by raymondk** [dfinity/http-proxy#13]
When the proxy app starts, the icon is not visible enough and it is hard to tell it is running:
<img width="111" alt="image" src="https://github.com/dfinity/http-proxy/assets/922020/1a765316-1271-4a82-95c9-479fe4c0b816">

<img width="151" alt="image" src="https://github.com/dfinity/http-proxy/assets/922020/fe0cc4b3-65a4-4b88-90b0-d644dd9c6a56">

mac os 13.3.1

**Comment by keplervital** [comment]
This [PR](https://github.com/dfinity/http-proxy/pull/20) fixes the issue, it leverages the [Template images](https://www.electronjs.org/docs/latest/api/native-image#template-image) that is supported on MacOSX to update the image according to the environment.
